### ISSUE TITLE
Zeal Support

### ISSUE THREAD

**Issue by trollixx** [blakeembrey/atom-dash#30]
Zeal now supports `dash-plugin://` scheme, and registers itself as a protocol handler on Windows and Linux.  The old `--query` argument has been deprecated, and will be removed in `0.3.0` release.

I'll [add](https://github.com/zealdocs/zeal/issues/448) support for `&prevent_activation=true` as well. I had no idea about this parameter. Zeal simply ignores unknown parameters, so starting to pass `&prevent_activation=true` immediately would not cause a problem.

I have just updated Zeal's [website](https://zealdocs.org/usage.html) with a link to this nice plugin.

**Comment by blakeembrey** [comment]
Ok, good to know. I'll make this change and release an update soon.

**Comment by blakeembrey** [comment]
@trollixx The `prevent_activation=true` makes sense for Dash because I use the background activation option for `open` already, as Dash has a mobile application that might be opened instead (from memory).

Anyway, my question is, do I need to open in the background (the "do not bring to forefront" option) for Zeal and, if so, what's that flag on linux using `xdg-open`?

**Comment by trollixx** [comment]
`xdg-open` [has no](http://linux.die.net/man/1/xdg-open) such option. So, the only way would be to handle `prevent_activation=true` in Zeal.

**Comment by blakeembrey** [comment]
@trollixx Thanks for the confirmation. If you have a chance, can you briefly check #31 (just that I'm using `xdg-open` correctly and how you'd expect). I'll merge and release once you review it.
