### ISSUE TITLE
apm troubles

### ISSUE THREAD

**Issue by beemo** [blakeembrey/atom-dash#47]
Looks like this package is currently trying to resolve to an internal 192.x.x.x IP?

`➜  /scripts apm install dash
Installing dash to /Users/bmo/.atom/packages Unable to download https://www.atom.io/api/packages/dash/versions/1.7.0/tarball: connect ETIMEDOUT 192.30.253.120:443`

Thanks in advance of your help.

**Comment by blakeembrey** [comment]
I believe this package has been published and stable for almost a year now without any such report, so I'd be inclined to say it's probably your configuration or an `apm` bug. Please make sure you don't have any proxying configuration or otherwise set up. I did a quick search and found https://github.com/atom/apm/issues/337 too.

**Comment by beemo** [comment]
Just tried again and it worked: 
`➜  /scripts apm install dash 
Installing dash to /Users/bmo/.atom/packages ✓`

Many thanks for your help, Blake.
